version: 2.1

jobs:
  build_and_test:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.16.0
    steps:
      - checkout

      - run:
          name: "Get Dependencies"
          command: flutter pub get

      - run:
          name: "Run Analyze"
          command: flutter analyze || true

      - run:
          name: "Run Tests"
          command: flutter test --coverage

      - run:
          name: "Build APK"
          command: flutter build apk --debug

workflows:
  version: 2
  test_and_build:
    jobs:
      - build_and_test